### ISSUE TITLE
[Feat] 명함 관련 뷰를 구현합니다.

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MC2-Team4-Atarashii#1]
### 📝 작업 목적

명함과 관련된 뷰를 구현합니다.

뷰 계층: 
MainTabView > MainNameCardTabView > MyCardView, CardCollectionView, CardTemplate

---

### 🛠️ Tasks

* [x] 명함 관련 뷰 파일 생성
* [x] iOS 16.0으로 프로젝트 버전 업데이트 

**MainTabView**
* [x] 하단 탭바 구현
* [x] 명함, 팀 탭 분리

**MainNameCardTabView**
* [x] MainNameCardTabView 내 segmented control 구현
* [x] 카테고리 선택에 따른 뷰 이동 로직 구현 (내 명함 / 수집한 명함 / 즐겨찾기)
* [ ] 상단 segmented control 위치 고정

**MyCardView**
* [x] 단일 명함 뷰 CardTemplate로 분리 후 연결
* [x] 스와이프 안내 문구 추가 

**CardCollectionView**
* [x] 슬라이드/갤러리 뷰 모드 필터링 로직 구현
* [ ] 슬라이드/갤러리 뷰 모드에 따른 뷰 그리기
* [x] 수집력 랭킹 배너 구현 
* [x] 랭킹 내용을 담은 모달 sheet 구현
* [x] 수집한 명함 리스트 뷰에 그리기 (더미 데이터)
* [ ] 카드 슬라이딩 애니메이션 구현

**CardTemplate**
* [x] 단일 명함 뷰 템플릿 구현
* [ ] 오전/오후 섹션 태그 구현 및 컴포넌트로 분리
* [ ] 명함 뒤집기 애니메이션 구현 (뒷면은 따로 이슈 파서 작업)
