### ISSUE TITLE
[Feat] 명함 리스트 관련 뷰의 디테일을 구현합니다.

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MC2-Team4-Atarashii#12]
### 📝 작업 목적

명함 리스트 관련 여러 시나리오를 대응하는 뷰 디테일을 구현합니다.
(명함 수정 시나리오 제외) 

---

### 🛠️ Tasks

**MainTabView**

- [ ] 탭 바 높이 줄이기

**MainNameCardTabView**

- [ ] 큐알 스캔으로 이어지는 floating 버튼 추가
- [x] 임시 유저 모델 생성 (국/영문 닉네임, 자기소개, 카드색상 등 포함)
- [ ] 상단 segmented control 위치 고정

**CardCollectionView**

- [ ] 카드 슬라이딩 애니메이션 구현
- [x] 갤러리 뷰 모드 구현

**CardTemplate**
- [x] 뒷면으로 가는 탭 애니메이션
	- [x] 수집한 명함, 즐겨찾기 카테고리에도 애니메이션 적용
	- [x] 탭 애니메이션 드래그 애니메이션으로 변경
- [x] 뒷면 뷰 구현 (리뷰로 가기 전까지)
- [x] 필터링 컨텍스트 메뉴 -> 메뉴로 변경
- [x] 내 명함, 타 러너의 명함 디테일 분기처리
- [x] 오전/오후 섹션 태그 구현
- [ ] 내 명함에 큐알 삽입
- [ ] 스위머 초기화면 카드랑 합치기 (텅뷰 for all segments)
- [ ] 명함 커스텀 디자인 (오버레이) 적용
