### ISSUE TITLE
[Feat] 명함 뷰에 큐알코드를 연결합니다. 

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MC2-Team4-Atarashii#20]
### 📝 작업 목적

내 명함 카드 뷰에 큐알코드를 연결하는 작업 및 기타 뷰 관련 디테일 작업을 진행합니다. 

---

### 🛠️ Tasks

**MainNameCardTabView**

* [x] 큐알 스캔으로 이어지는 floating 버튼 추가

**CardCollectionView**

 * [ ] 카드 슬라이딩 애니메이션 구현

**CardTemplate**

 * [x] 내 명함에 큐알 삽입
 * [ ] 스위머 초기화면 카드랑 합치기 (텅뷰 for all segments)
 * [ ] 명함 커스텀 디자인 (오버레이) 적용
