### ISSUE TITLE
[feat] 명함 내용 수정뷰 및 인트로 전체 뷰의 스타일 디테일 추가

### ISSUE THREAD

**Issue by Jhwan2** [DeveloperAcademy-POSTECH/MC2-Team4-Atarashii#21]
### 📝 작업 목적
스타일 디테일 추가

---

### 🛠️ Tasks

* [x] 명함 내용 수정 뷰 텍스트필드 디테일 추가
* [x] 명함 내용 수정 뷰 나머지 색, 전체적인 위치와 디테일 수정 
* [ ] 닉네임생성 뷰 나머지 색, 전체적인 위치와 디테일 수정 
* [x] 시간생성 뷰 나머지 색, 전체적인 위치와 디테일 수정
