### ISSUE TITLE
[Feat] 명함 디자인 수정 뷰를 구현합니다.

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MC2-Team4-Atarashii#24]
### 📝 작업 목적

명함 수정 뷰 중 하나인 EditCardDesignView를 구현합니다. 

---

### 🛠️ Tasks

* [x] 명함 꾸미기 디테일 뷰 구현
* [ ] 명함 컬러, 명함 패턴 선택 로직 구현
* [x] 미모지 API 연결 (UIViewRepresentable 통해 SwiftUI에 UIKit 코드 사용)
* [ ] 미모지 데이터로 저장하는 로직 구현
