### ISSUE TITLE
[Feat] CardGenerateSelectRoleGoalView 구현

### ISSUE THREAD

**Issue by earlysummer0303** [DeveloperAcademy-POSTECH/MC2-Team4-Atarashii#29]
### 📝 작업 목적

카드 생성 뷰에서, 자신의 역할 목표를 고르는 (ex) iOS 개발자, UI/UX 디자이너...) 뷰 및 직접 입력을 위한 모달 sheet 뷰를 구현합니다.

---

### 🛠️ Tasks

* [x] SelectRoleGoalView 구현 (부모뷰)
* [ ] RoleGoalInputSheetView 구현 (자식뷰)
* [ ] binding을 통한 부모뷰 - 자식뷰 간 데이터 전달 로직 구현
