### ISSUE TITLE
[Feat] 명함 디자인 수정 뷰의 커스텀 패널을 구현합니다. 

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MC2-Team4-Atarashii#38]
### 📝 작업 목적

EditCardDesignView 하단의 커스텀 창을 구현합니다.

---

### 🛠️ Tasks

* [x] 컬러 커스텀 창
	- [x] 컬러 선택 UI 구현
	- [x] 브랜드 컬러 변수로 분기처리
* [x] 패턴 커스텀 창
	- [x] 패턴 선택 UI 구현
	- [x] cardPatternIconList, cardPatternList Enum 생성 후 뷰 분기처리
	- [x] 임시 패턴 데이터 연결

아바타 이미지 
* [x] 외부 소스인 MemojiView를 이용해 Memoji 데이터 연결 시도
* [x] Memoji 대신 Emoji를 받아오는 UIEmojiTextField 사용
	- [x] 커스텀 TextField 
		- [x] emoji 단일 입력값 
		- [x] character 개수 제한
		- [x] TextField cursor 숨김 처리
