### ISSUE TITLE
[Feat] SelectCollaborationKeywordView 뷰 및 로직 구현

### ISSUE THREAD

**Issue by earlysummer0303** [DeveloperAcademy-POSTECH/MC2-Team4-Atarashii#59]
### 📝 작업 목적

나와 어울리는 협업 키워드를 고르는  SelectCollaborationKeywordView 뷰를 구현합니다.

---

### 🛠️ Tasks

* [ ]SelectCollaborationKeywordView 뷰를 구현
* [x] 원형 키워드를 누르면 커지는 모션 구현
* [ ] 선택된 키워드 값을 받는 로직 구현

**Comment by earlysummer0303** [comment]
선택된 키워드 값을 받는 로직 구현은 다음 이슈에서 해결 예정.
