### ISSUE TITLE
[Refactor] 명함 뷰 관련 연결 및 세부 디테일 작업을 진행합니다. 

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MC2-Team4-Atarashii#63]
### 📝 작업 목적

- 메인 카드 뷰에 이미 존재하는 초기화면을 case에 따라 연결합니다. 
- 메인 카드 뷰의 디테일을 조정합니다. 
- 작업 완료된 뷰를 연결합니다. 
 MainView > MainTabView > MainNameCardView > InitialCardMainView > CardGenerateTextEditorView 

---

### 🛠️ Tasks

* [x] cardViewCategories Enum에 의해 화면 분기처리 및 초기화면 연결
* [x] Segmented Control 위치 화면 상단에 고정 (absolute positioning 적용)
* [x] MyCardView > 스와이프 안내 문구에 깜빡이는 애니메이션 추가
* [x] 최상위 MainTabView에서 NavigationStack을 추가해 뷰 연결
* [x] EmojiTextField 파일 위치 이동
