### ISSUE TITLE
[Refactor] 명함 관련 뷰 디테일 통일 작업을 진행합니다. 

### ISSUE THREAD

**Issue by lianne-b** [DeveloperAcademy-POSTECH/MC2-Team4-Atarashii#73]
### 📝 작업 목적

명함과 관련된 뷰들의 디테일(segmented control, 애니메이션 등)을 수정합니다. 

---

### 🛠️ Tasks

* [x] MainNameCardTabView > segmented control 디자인 수정
* [x] cardTemplate의 플립 애니메이션 수정
* [x] 패턴 이미지 어셋 추가 및 뷰 연결
